server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.102:8761/eureka/
    heartbeat:
      enable: true
  instance:
    preferIpAddress: true #是否将eureka自身作为应用注册到eureka注册中心
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #为true时，可以启动，但报异常：Cannot execute request on any known server
spring:
  application:
    name: zuul #为你的应用起个名字，该名字将注册到eureka注册中心
zuul:
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 10000
  #路由配置
  routes:
    farm:
      path: /farm/**
      #eureka 管理上面的名称
      serviceId: farm
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000






