#端口号相关配置
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.102:8761/eureka/
    heartbeat:
      enable: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: farm
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#配置mysql数据源
mysql:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root